// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductsData.Entities;

#nullable disable

namespace ProductsData.Migrations
{
    [DbContext(typeof(ProductDbContext))]
    [Migration("20221121124453_init00")]
    partial class init00
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProductsData.Entities.Product", b =>
                {
                    b.Property<int>("productId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("productId"));

                    b.Property<string>("country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("price")
                        .HasColumnType("int");

                    b.Property<int?>("productTypeid")
                        .HasColumnType("int");

                    b.HasKey("productId");

                    b.HasIndex("productTypeid");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            productId = 1,
                            country = "COLOMBIA",
                            name = "Spoon",
                            price = 32
                        },
                        new
                        {
                            productId = 2,
                            country = "CROATIA",
                            name = "Bycicle",
                            price = 569
                        },
                        new
                        {
                            productId = 3,
                            country = "ITALY",
                            name = "Necklace",
                            price = 1600
                        },
                        new
                        {
                            productId = 4,
                            country = "FRANCE",
                            name = "Water",
                            price = 5
                        },
                        new
                        {
                            productId = 5,
                            country = "ITALY",
                            name = "Chair",
                            price = 260
                        });
                });

            modelBuilder.Entity("ProductsData.Entities.ProductType", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("ProductTypes");

                    b.HasData(
                        new
                        {
                            id = 1,
                            type = "Kitchen Utensils"
                        },
                        new
                        {
                            id = 2,
                            type = "Transportation"
                        },
                        new
                        {
                            id = 3,
                            type = "Jewlery"
                        },
                        new
                        {
                            id = 4,
                            type = "Consumables"
                        },
                        new
                        {
                            id = 5,
                            type = "Furniture"
                        });
                });

            modelBuilder.Entity("ProductsData.Entities.Product", b =>
                {
                    b.HasOne("ProductsData.Entities.ProductType", "productType")
                        .WithMany()
                        .HasForeignKey("productTypeid");

                    b.Navigation("productType");
                });
#pragma warning restore 612, 618
        }
    }
}
