// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductsData.Entities;

#nullable disable

namespace ProductsData.Migrations
{
    [DbContext(typeof(ProductDbContext))]
    [Migration("20221109205823_newMigration3")]
    partial class newMigration3
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ProductsData.Entities.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"), 1L, 1);

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int?>("ProductTypeTypeId")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.HasIndex("ProductTypeTypeId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            Country = "COLOMBIA",
                            Id = 1,
                            Name = "Spoon",
                            Price = 32
                        },
                        new
                        {
                            ProductId = 2,
                            Country = "CROATIA",
                            Id = 2,
                            Name = "Bycicle",
                            Price = 569
                        },
                        new
                        {
                            ProductId = 3,
                            Country = "ITALY",
                            Id = 3,
                            Name = "Necklace",
                            Price = 1600
                        },
                        new
                        {
                            ProductId = 4,
                            Country = "FRANCE",
                            Id = 4,
                            Name = "Water",
                            Price = 5
                        },
                        new
                        {
                            ProductId = 5,
                            Country = "ITALY",
                            Id = 5,
                            Name = "Chair",
                            Price = 260
                        });
                });

            modelBuilder.Entity("ProductsData.Entities.ProductType", b =>
                {
                    b.Property<int>("TypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TypeId"), 1L, 1);

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TypeId");

                    b.ToTable("ProductTypes");

                    b.HasData(
                        new
                        {
                            TypeId = 1,
                            Type = "Kitchen Utensils"
                        },
                        new
                        {
                            TypeId = 2,
                            Type = "Transportation"
                        },
                        new
                        {
                            TypeId = 3,
                            Type = "Jewlery"
                        },
                        new
                        {
                            TypeId = 4,
                            Type = "Consumables"
                        },
                        new
                        {
                            TypeId = 5,
                            Type = "Furniture"
                        });
                });

            modelBuilder.Entity("ProductsData.Entities.Product", b =>
                {
                    b.HasOne("ProductsData.Entities.ProductType", "ProductType")
                        .WithMany()
                        .HasForeignKey("ProductTypeTypeId");

                    b.Navigation("ProductType");
                });
#pragma warning restore 612, 618
        }
    }
}
